### ISSUE TITLE
Rainbow Laser doesn't work as of last patch

### ISSUE THREAD

**Issue by InfamousMyzt** [JamesWilko/GoonMod#102]
I don't know if OK changed the way laser code works or what, but rainbow lasers now either show invisible or as a white laser for me.

**Comment by JamesWilko** [comment]
Can't reproduce locally. Are you sure you didn't turn your saturation/value all the way up/down by accident? Is there an error in your logs in `mods/logs/` when attempting to use the laser? Are you running any other mods, including any that might not change the colours of lasers?

**Comment by InfamousMyzt** [comment]
Not even sure what it was at this point. I couldn't get it to work at all
for days, then I played around with values a ton and finally fixed it.
Probably consider it closed until I can recreate whatever it was doing.
