### ISSUE TITLE
Cannot finish hosted/solo heist

### ISSUE THREAD

**Issue by Kilobytz** [JamesWilko/GoonMod#103]
When I have finished a heist, the game gets stuck saying "calculating XP" after calculating the money, and does not change, I disabled my mods, and when trying heists with them one by one, the issue only happened with GoonMod.  This has only happened since the last update, and when I am host, however I have only hosted games and am unsure of whether it this happens to all types of games.

**Comment by InfamousMyzt** [comment]
Same happened to me, although I have assumed that it's gagehud.

**Comment by JamesWilko** [comment]
I can't reproduce this locally. If you play the heist and get this again, please check your log files in `mods/logs/` for any errors and include them.

**Comment by Kilobytz** [comment]
I got an error, 
06:42:07 PM FATAL ERROR: mods/GoonMod/mods/gage_coins.lua:175: attempt to index upvalue 'ExtendedInv' (a nil value)
