### ISSUE TITLE
Inventory scrolling

### ISSUE THREAD

**Issue by Vielmann** [JamesWilko/GoonMod#104]
In the Inventory, you can use the mouse wheel to scroll through the pages.
![pages](https://cloud.githubusercontent.com/assets/14875415/10140695/1c9c475e-6609-11e5-887f-c886ccae5b7b.png)
In Goonmod this doesn't work.

**Comment by InfamousMyzt** [comment]
Can confirm, this is a bug. Pages should scroll no matter where your mouse is, but with goon it still has to be at the top of the page like before the inventory update.

**Comment by goontest** [comment]
replace BlackMarketGUI.lua with the below
https://github.com/goontest/GoonMod/blob/master/GoonMod/lua/BlackMarketGUI.lua
or replace
local inside_tab_area = self._tab_area_panel:inside(x, y)
with 
local inside_tab_area = not self._tab_area_panel:inside(x, y) and self._tabs[self._selected] and not self._tabs[self._selected]:has_scroll_bar()
