### ISSUE TITLE
Weapon Customization

### ISSUE THREAD

**Issue by zyphilus** [JamesWilko/GoonMod#114]
I can't seem to use colors or patterns even after installing Goon Mod, but laser and flashlight colors are working fine.
![2015-10-27_00002](https://cloud.githubusercontent.com/assets/15336488/10756060/874200b4-7cdc-11e5-85bf-d764858a3cc1.jpg)

**Comment by sebastiangabl** [comment]
I guess it's just because of the new Inventory and will be fixed. My old cusomisations are still there and visible when I click preview.

**Comment by SinZ163** [comment]
in the main inventory screen, you can right click on the primary / secondary / melee categories and will bring up the weapon customization for that weapon.
