### ISSUE TITLE
BlackMarketGUI Crash

### ISSUE THREAD

**Issue by SteamedRevenge** [JamesWilko/GoonMod#116]
Application has crashed: C++ exception
[string "lib/managers/menu/blackmarketgui.lua"]:5747: attempt to index field '?' (a nil value)

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                         ntdll  (???)     RtlQueryPackageClaims                               

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.43.1
	CPU : Intel(R) Pentium(R) CPU G3240 @ 3.10GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GT 630 / nvd3dum.dll[10.18.13.5354]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     44046    0MB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Headset Earphone (Microsoft LifeChat LX-3000))

Keeps crashing because of the blackmarketgui.lua

**Comment by karasuhebi** [comment]
Yep, I'm getting the same thing. I think it's related to the Weapon Customizer but I'm not sure.

**Comment by SteamedRevenge** [comment]
The files in GoonMod/menu and it could be related to that. It's pissing me off as I can't customise my shotguns or my Smgs as it crashes if I try to select a tab in the black market.

**Comment by SteamedRevenge** [comment]
I'm talking about the blakmarketgui thing

**Comment by SteamedRevenge** [comment]
Yea he needs to fix it asap

**Comment by JamesWilko** [comment]
This isn't helpful unless you tell me where in the game you were when you got the crash, what you were doing, and what other mods you have installed.

**Comment by SteamedRevenge** [comment]
BLT MODS

PocoHUD
GoonMod
BetterBots
Skin Unlocker

And this crash happened before I installed Skin unlocker so it's not that mods fault.
The crash happens when I go on certain weapon mod categories or weapons.
I click the barrel tab or some other tab and the game crashes.

**Comment by SteamedRevenge** [comment]
Also quote on this
"
Yep, I'm getting the same thing. I think it's related to the Weapon Customizer but I'm not sure.

I'd like to add that in the GoonMod.txt file in the logs folder, there's this line:
"[GoonMod][Error] Could not open file 'mods/GoonMod/lua/CosmeticsWeaponBase.lua'! Does it exist, is it readable?"

FWIW, that file is not in my GoonMod/lua/ folder.
"

**Comment by SteamedRevenge** [comment]
Please fix this issue as it doesn't let me modify my shotguns or smgs :(

**Comment by SteamedRevenge** [comment]
Also we have to force load goonmod as you haven't updated the thing to remove that it's disabled

**Comment by SteamedRevenge** [comment]
I dont get the crash anymore after r22

**Comment by karasuhebi** [comment]
@JamesWilko The crashes seem to be fixed now with r22. Thanks for the quick fix! I would imagine the answer to this is "no" but would you still like a list of my mods and when the crash used to happen?
