### ISSUE TITLE
Reticle Issue

### ISSUE THREAD

**Issue by InnocentBystandr** [JamesWilko/GoonMod#118]
The Aiming reticle is being forced to red-dot. 
This is quite annoying.

If you could at least point me where to look to fix this, that'd be great.

**Comment by JamesWilko** [comment]
This was fixed some time ago in commit [572b823](https://github.com/JamesWilko/GoonMod/commit/572b823abbf2ee4ae976cb78caa9013186b25f7b). You either have not updated, or you've installed a mod that's incompatible and is causing the issue.
