### ISSUE TITLE
BlackMarketGUI.lua crashes game when attempting to purchase items after U94.3

### ISSUE THREAD

**Issue by EchoWaves1995** [JamesWilko/GoonMod#120]
It seem as though goonmods been hit by U94.3, here is the crash log if it helps
[2016_02_04_log.txt](https://github.com/JamesWilko/GoonMod/files/118326/2016_02_04_log.txt)
//Crash Log
Application has crashed: C++ exception
mods/GoonMod/lua/BlackMarketGUI.lua:1759: attempt to index field '?' (a nil value)

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.47.4
	CPU : Intel(R) Core(TM) i3-2120 CPU @ 3.30GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 10.0 
	GPU : AMD Radeon HD 7700 Series / aticfx32.dll[8.17.10.1429]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     44052    0MB
	OS : 6.1.7601 (Service Pack 1) 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Logitech, Inc. (Speakers (7- Logitech G430 Gaming Headset))

**Comment by karasuhebi** [comment]
Came here to report this same issue.

**Comment by JamesWilko** [comment]
Fixed as of r25.
