### ISSUE TITLE
Bug with deagle and steam inventory

### ISSUE THREAD

**Issue by Afbg123** [JamesWilko/GoonMod#121]
When enabling weapon customization, goonmod adds a blank deagle to the steam inventory. When trying to modify the deagle, the game crashes with this message: 

Application has crashed: C++ exception
[string "lib/managers/menu/blackmarketgui.lua"]:11155: attempt to compare string with number.

**Comment by JamesWilko** [comment]
This is a conflict with another mod. Please post your **complete** BLT mods list.

**Comment by Afbg123** [comment]
I have tested with and without any mods, and while getting rid of the skin unlocker mod allows me to enter the weapon customization menu without crashing, the Goonmod weapon skin of the deagle still remains in the steam inventory, despite it not supposed to appear there.

Screenshot: http://i.imgur.com/pjUEo7V.jpg. Also when selecting "edit goonmod skin" in weapon customization, the red "epic" icon appears rather than the standard weapon icon. This only appears to be an issue with the deagle.
