### ISSUE TITLE
Crash when trying to customize weapons

### ISSUE THREAD

**Issue by Afbg123** [JamesWilko/GoonMod#122]
Crash on Update 95 when clicking any of the tabs in the weapon customization menu:

Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main
Script stack:
                   show_btns()  lib/managers/menu/blackmarketgui.lua:7876           
            set_selected_tab()  lib/managers/menu/blackmarketgui.lua:7287           
               mouse_pressed()  lib/managers/menu/blackmarketgui.lua:7103           
ddi_original_blackmarketgui_mousepressed()  @mods/GoonMod/lua/BlackMarketGUI.lua:1699           
               mouse_pressed()  @mods/Drag                                          
                                and                                                 
                          Drop                                                      
Inventory/blackmarketgui.lua:5  mouse_pressed()                                     
                                lib/managers/menu/menucomponentmanager.lua:1035     
               mouse_pressed()                                                      
@mods/base/lua/MenuComponentManager.lua:24  mouse_pressed()                                     
                                lib/managers/menu/menurenderer.lua:366              
lib/managers/menu/menuinput.lua:536  ()                                                  
                        =(tail                                                      
                      call):-1  lib/managers/mousepointermanager.lua:308            
                            ()  =(tail                                              
                                call):-1

**Comment by JamesWilko** [comment]
Fixed as of r26/27.
