### ISSUE TITLE
Crash when Excessive Force or National Guard Response is enabled

### ISSUE THREAD

**Issue by Jindetta** [JamesWilko/GoonMod#126]
Game will crash just before police assault begins
Issue is at **mutators/mutator_spawn_adjustments.lua**

If you remove **GroupAIStateBesiege:_upd_group_spawning()** function,
it works almost perfectly so they must have changed how this works in recent patch

**Comment by JamesWilko** [comment]
Mutators are now an official feature, so GoonMod mutators have been removed. Closing all issues relating to mutators.
