### ISSUE TITLE
Crash when opening weapon customization screen in update 97.4

### ISSUE THREAD

**Issue by WindowDump** [JamesWilko/GoonMod#127]
As of update 97.4, I've found that every time I attempt to open the weapon customization screen, either from the main inventory screen or from the weapon skin tab, Payday 2 crashes. This applies to both weapons that have no customization applied, as well as ones that do: it's the same crash every time.

I don't see any errors in the mods/logs folder.

crash.txt
-------------------------------

Application has crashed: C++ exception
mods/GoonMod/lua/BlackMarketGUI.lua:1452: attempt to index field '?' (a nil value)

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                         ntdll  (???)     RtlQueryPerformanceCounter                          
                         ntdll  (???)     RtlQueryPerformanceCounter                          
                         TfWah  (???)     ???                                                 
                      kernel32  (???)     WakeConditionVariable                               
                    KERNELBASE  (???)     VirtualQueryEx                                      
                    KERNELBASE  (???)     VirtualQuery                                        
                      kernel32  (???)     SetUnhandledExceptionFilter                         
                      kernel32  (???)     SetUnhandledExceptionFilter                         
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                      kernel32  (???)     BaseThreadInitThunk                                 
                         ntdll  (???)     RtlInitializeExceptionChain                         
                         ntdll  (???)     RtlInitializeExceptionChain                         
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.50.4
	CPU : Intel(R) Core(TM) i5-4670K CPU @ 3.40GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 10.0 
	GPU : NVIDIA GeForce GTX 770 / nvd3dum.dll[10.18.13.6472]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     416322    0MB
	OS : 6.1.7601 (Service Pack 1) 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Razer (Speakers (Razer Surround Audio Controller))

**Comment by Isotaupe** [comment]
This crash also appears to occur when attempting to customize a mask.

**Comment by Isotaupe** [comment]
Issue seems resolved with r29

**Comment by WindowDump** [comment]
I just did a quick test and everything looks like it's working again.
