### ISSUE TITLE
Attempting to make a new mod.

### ISSUE THREAD

**Issue by NoLegs** [JamesWilko/GoonMod#131]
I made a mistake and made a question in the wrong area, and I do not know how to remove it, Just in case I commented it again below, but sorry for the issue.

**Comment by NoLegs** [comment]
I am attempting to make election day 2 right track "swing vote" map as it is my favorite, so far with no avail. (I removed all mods from the process and yet I still cannot get it correct.


06:28:33 PM Log: CURL INITD
06:28:38 PM Log: Initiating Hook
06:28:42 PM Log: Initiating Hook
06:28:42 PM Lua: [Warning] Could not load file 'mods/saves/mod_updates.txt', no data loaded...
06:28:42 PM Lua: [Mods] Loading mods for state (table: 001C0460)
06:28:42 PM Lua: [Mods] Loading mod: base...
06:28:42 PM Lua: [Mods] Loading mod: Election Day 2 Standalone...
06:28:42 PM Log: Initiating Hook
06:28:42 PM Lua: [Warning] Could not load file 'mods/saves/mod_updates.txt', no data loaded...
06:28:42 PM Lua: [Mods] Loading mods for state (table: 001C04A0)
06:28:42 PM Lua: [Mods] Loading mod: base...
06:28:42 PM Lua: [Mods] Loading mod: Election Day 2 Standalone...
06:28:43 PM Log: Initiating Hook
06:28:43 PM Lua: [Warning] Could not load file 'mods/saves/mod_updates.txt', no data loaded...
06:28:43 PM Lua: [Mods] Loading mods for state (table: 1CCF2000)
06:28:43 PM Lua: [Mods] Loading mod: base...
06:28:43 PM Lua: [Mods] Loading mod: Election Day 2 Standalone...
06:28:44 PM Log: Incoming HTTP Request/Request
06:28:44 PM Log: http://api.paydaymods.com/updates/retrieve/?mod[0]=payday2blt&mod[1]=payday2bltdll
06:28:44 PM Log: 790
06:28:44 PM Log: Launching Async HTTP Thread
06:28:44 PM Lua: [Updates] Attempting to remove temporary hook dll...
06:28:44 PM Lua: [Warning] Could not remove hook dll: IPHLPAPI_temp.dll: No such file or directory
06:28:45 PM Lua: [Updates] Received update data for 'payday2blt', server revision: 12
06:28:45 PM Lua: [Updates] Received update data for 'payday2bltdll', server revision: 5
06:28:57 PM Log: Initiating Hook
06:28:57 PM Lua: [Warning] Could not load file 'mods/saves/mod_updates.txt', no data loaded...
06:28:57 PM Lua: [Mods] Loading mods for state (table: 1DA11040)
06:28:57 PM Lua: [Mods] Loading mod: base...
06:28:57 PM Lua: [Mods] Loading mod: Election Day 2 Standalone...
06:28:57 PM Log: Initiating Hook
06:28:57 PM Lua: [Warning] Could not load file 'mods/saves/mod_updates.txt', no data loaded...
06:28:57 PM Lua: [Mods] Loading mods for state (table: 21011700)
06:28:57 PM Lua: [Mods] Loading mod: base...
06:28:57 PM Lua: [Mods] Loading mod: Election Day 2 Standalone...
06:28:57 PM Log: Initiating Hook
06:28:57 PM Lua: [Warning] Could not load file 'mods/saves/mod_updates.txt', no data loaded...
06:28:57 PM Lua: [Mods] Loading mods for state (table: 27FB0400)
06:28:57 PM Lua: [Mods] Loading mod: base...
06:28:57 PM Lua: [Mods] Loading mod: Election Day 2 Standalone...
06:28:59 PM Log: CURL CLOSED






Any Ideas?

**Comment by JamesWilko** [comment]
Unfortunately I can't help you since the log posted doesn't have any errors in it, and I don't do heist conversions like this either. Your best bet would be to ask on the [Steam Payday 2 modding subforum](http://steamcommunity.com/app/218620/discussions/15/), or on LastBullet since people there have done this type of thing before.

I'm also going to close the issue since it's not specifically a GoonMod issue.
