### ISSUE TITLE
Inventory crash with Update 121

### ISSUE THREAD

**Issue by Afbg123** [JamesWilko/GoonMod#138]
When attempting to modify a weapon with the Halloween 2016 update, Goonmod causes the game to crash. Crashlog:

Application has crashed: C++ exception
[string "lib/managers/menu/blackmarketgui.lua"]:814: attempt to index field '?' (a nil value)

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlAllocateHeap

**Comment by Andreybest** [comment]
Same thing. Opening MG42 and "Crash"

**Comment by Joker9944** [comment]
Do you have Gage Coin shop enabled? Probably a conflict with the new Continental Coin mod buy feature.

Also it's kinda hilarious how Overkill copies all the functionalities from GoonMod.

**Comment by JamesWilko** [comment]
Should be fixed in r32. @Joker9944 I work for Overkill.
