### ISSUE TITLE
Accuracy counter

### ISSUE THREAD

**Issue by DarKobalt** [JamesWilko/GoonMod#18]
Hi,

I'm using a mix of HoxHUD, PocoHUD and GoonMod. Since the last update, the accuracy counter (tab view) doesn't display correctly and is always at 0%. It occurs only with people who have poco/goon. HoxHUD only users doesn't have this, and yet Goon is the only mod which got updated recently.

(And there's a bug, maybe from incompatibility, that makes the enemy damage counter from HoxHUD renders always 0.0 HP, but I guess that's none of your buisness)

**Comment by JamesWilko** [comment]
This should be fixed in the next update.

**Comment by DarKobalt** [comment]
Thanks for the reply. Will the HoxHUD enemy counter get repaired too, or it's not goonmod related?

**Comment by JamesWilko** [comment]
I haven't tried with HoxHud, but the change will probably fix the issue. If it doesn't, let me know and I'll take a more indepth look tomorrow.

**Comment by DarKobalt** [comment]
Okay, I'll wait for the update and leave a reply here!

**Comment by DarKobalt** [comment]
Everything seems fine now, good job! ^^
