### ISSUE TITLE
Hooks:Unregister(id) doesn't work the way you seem to think

### ISSUE THREAD

**Issue by miguelmig** [JamesWilko/GoonMod#19]
```lua
function Hooks:Unregister( id )

	for k, v in pairs(self.registered_hooks) do
		if k[id] ~= nil then
			k[id] = nil
		end
	end

end
```

This function won't remove the hook with that ID, it actually won't do anything unless the id happens to be the same as a key in the table ( with is unlikely as long as you use string keys and number ids )

Test code:
```lua
function print_table (tt)
	if type(tt) == "table" then
		for key, value in pairs (tt) do
			if type (value) == "table" then
				print(string.format("<%s> => table", tostring (key)));
				print_table (value)
			else
				print(string.format("[%s] => %s", tostring (key), tostring(value)))
			end
		end
	else print(tt) end
end

Hooks = {}
Hooks.registered_hooks = {}

function Hooks:Unregister( id )

	for k, v in pairs(self.registered_hooks) do
		if k[id] ~= nil then
			k[id] = nil
		end
	end

end

function Hooks:Add( key, id, func )
	self.registered_hooks[key] = self.registered_hooks[key] or {}
	self.registered_hooks[key][id] = func
end

Hooks:Add("Event1", 1, function() end)
Hooks:Add("Event2", 2, function() end)
print_table(Hooks.registered_hooks)
Hooks:Unregister(1)
print("After removal:")
print_table(Hooks.registered_hooks)
```

You can [try it yourself](http://www.lua.org/cgi-bin/demo)

**Comment by JamesWilko** [comment]
Unregister is for removing all of the hooked functions that are called when a specified hook runs, so your use of Unregister to try and remove "1" is incorrect. You should be using Remove to remove the hook "1" or use unregister to remove the entire "Event1" set.
However, since none of this is documented, and Unregister was broken anyway, I apologize! Fix for Unregister is on the way with the next update.

**Comment by miguelmig** [comment]
No worries, I was just browsing throught the code and that didn't seem correct to me so I decided to test it. Good luck with the mod :+1:

**Comment by JamesWilko** [comment]
Thanks a ton for pointing it out, it'd probably have gone unnoticed for much longer if you didn't.
