### ISSUE TITLE
Selecting a material that you don't have crashes game.[Weapon Customization] 

### ISSUE THREAD

**Issue by 71NK** [JamesWilko/GoonMod#20]
title.

**Comment by JamesWilko** [comment]
Can you upload your log file and your Payday 2 crashlog.txt from '%appdata%/Local/Payday 2'? I can't reproduce this locally, so I need the log to fix the issue.

**Comment by 71NK** [comment]
could you tell me how to upload files on this site? i'm not so familiar on how it all works

**Comment by 71NK** [comment]
i found this in my payday 2 file

might be of some help

Post Require Script for: * - Script: GoonBase/goonbase.lua
[Mods] Loading Mods
[Mods] Registering mod 'CustomWaypoints'
[Mods] Registering mod 'TrainHeistPlans'
[Mods] Registering mod 'BlackmarketModShop'
[Mods] Registering mod 'BodyCountMod'
[Mods] Registering mod 'CustomWeaponLaser'
[Mods] Registering mod 'CustomWorldLaserColour'
[Mods] Registering mod 'GageCoins'
[Mods] Registering mod 'WeaponCustomization'
[Mods] Registering mod 'IronsightSensitivity'
[Mods] Registering mod 'RememberGadgetState'
[Mods] Registering mod 'CustomWeaponFlashlight'
[Mods] Registering mod 'PushToInteract'
[Mods] Registering mod 'ExtendedInventory'
[Mods] Registering mod 'Trading'
[Mods] Registering mod 'GameColourGrading'
[Mods] Registering mod 'CustomEnemyWeaponLaser'
[Mods] Registering mod 'GameplayMutators'
[Mods] Registering mod 'GrenadeIndicator'
[Mods] Setting up mods
[Mutators] Loading Mutators
[Mutators] Registering mutator 'MethAddiction'
[Mutators] Registering mutator 'AllTaserSpawns'
[Mutators] Registering mutator 'AllBulldozerSpawns'
[Mutators] Registering mutator 'AllShieldSpawns'
[Mutators] Registering mutator 'SuicidalSpawnRateCops'
[Mutators] Registering mutator 'BulldozersWithShields'
[Mutators] Registering mutator 'AllBulletsExplode'
[Mutators] Registering mutator 'InsaneSpawnRate'
[Mutators] Registering mutator 'InsaneSpawnRateCops'
[Mutators] Registering mutator 'FloatingBodies'
[Mutators] Registering mutator 'AllLightningSpeed'
[Mutators] Registering mutator 'RealismMode'
[Mutators] Registering mutator 'SuicideCloakers'
[Mutators] Registering mutator 'Unbreakable'
[Mutators] Registering mutator 'SuicidalSpawnRate'
[Mutators] Registering mutator 'WeaponsJam'
[Mutators] Registering mutator 'AllCloakerSpawns'
[Mutators] Registering mutator 'NoAmmoPickups'
[Mutators] Registering mutator 'Instagib'
[Mutators] Setting up mutators
[Update] Requesting update version...
https://raw.githubusercontent.com/JamesWilko/GoonMod/master/update_version.txt
[Update] Received callback: true
[Update] Versions - Local: 23 / Remote: 23
[Warning] Could not load weapon customization, no visual blueprint specified
[Warning] Could not load weapon customization, no visual blueprint specified
[Warning] Could not load weapon customization, no visual blueprint specified

**Comment by JamesWilko** [comment]
You'll have to upload your crashlog.txt to a file or text hosting site, such as Pastebin. Or you can email it directly to me. You can find my email by clicking my name.
I'll need the crashlog from your appdata Payday folder, since there is nothing out of the ordinary with the log above.

**Comment by 71NK** [comment]
http://pastebin.com/KavEMckJ
Do note that i have PocoHud alongside with GoonMod

**Comment by JamesWilko** [comment]
Thanks, I see where the problem lies, and I'll put a fix out with the next update.
Do you have both the Gage Mod Shop, and the Extended Inventory mods enabled?

**Comment by 71NK** [comment]
I think i turned it off.

**Comment by JamesWilko** [comment]
Try turning the Extended Inventory back on, it looks like the Mod Shop isn't disabling itself correctly, and is causing the issues that you're having.

**Comment by 71NK** [comment]
ill try that tomorrow, going to sleep right now.
ill message you the result

**Comment by 71NK** [comment]
bit late but i indeed had it off.
and turning it back on fixed it.
