### ISSUE TITLE
National Guard Response

### ISSUE THREAD

**Issue by ezequiel** [JamesWilko/GoonMod#29]
First off, thanks for the awesome mod. My friends and I are having tons of fun using it!

I'm not sure if it's just me, but when I enable this option; the cops that spawn seem to never move. And if they do move, it's only if they spot me, or after a very long delay. The cops also seem to be way less aggressive than they normally are (I enabled this option on Death Wish). Is this intentional?

Thanks

**Comment by FlunkyDave** [comment]
Sadly, yes. The cops are very, VERY defensive instead of Offensive, as I hoped them to be.


PS: Would it be possible to enable the Titandozer from April Fools?

**Comment by MeneXia** [comment]
Titandozer was a joke, and was not actually developed or is in-game.

**Comment by FlunkyDave** [comment]
Aww.

**Comment by AlfieSR** [comment]
Actually the headless halloween dozers were called "Titandozers" for the second halloween event. Is it possible to re-enable them or, like the heist, are they hard-limited to the event?

**Comment by JamesWilko** [comment]
They're limited to the event map, so it's not possible to re-add them as regular enemies.

**Comment by JamesWilko** [comment]
Mutators are now an official feature, so GoonMod mutators have been removed. Closing all issues relating to mutators.
