### ISSUE TITLE
Game crashing on Mask screen

### ISSUE THREAD

**Issue by bakarafa** [JamesWilko/GoonMod#31]
After last update my game is crashing when i click Mask option to change my mask. As i say in my other thread, i just sent my "Preferred Character" masks to a friend. Maybe the problem is related to that?
Thanks bro

Edit: Crashlog here

Application has crashed: C++ exception
[string "lib/managers/menu/blackmarketgui.lua"]:668: attempt to index field '?' (a nil value)

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.23.3
	CPU : Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz (4 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 10.0 
	GPU : AMD Radeon R9 200 Series / aticfx32.dll[8.17.10.1333]
	Language : @ID94cca2fdaccfc2cd@
	Memory : 8169    MB
	OS : 6.1.7601 (Service Pack 1) 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Alto-falantes (Realtek High Definition Audio))

**Comment by JamesWilko** [comment]
Put a fix in, if you do a forced redownload you should be able to get this fixed on your end before the next update.
Go to your GoonMod options menu, click Check for Updates, and then click Force Redownload to update to the latest files that weren't included in the update. Then if you open, close, and then reopen your inventory you should have access to your masks tab, and the Preferred Character mask again.

**Comment by bakarafa** [comment]
Fixed.
Thanks for the quick fix and answer!
