### ISSUE TITLE
Weapon Customization

### ISSUE THREAD

**Issue by FlunkyDave** [JamesWilko/GoonMod#32]
I've tried my best to get this "Weapon Customization" to work, but when I try it, it shows all parts as "Not-Modifiable". Even though this is a great mod, I wished this would work.

**Comment by JamesWilko** [comment]
You need to select the parts you want to customize by clicking them. Select parts from the "Not Modifying" list to swap them to the "Modifying" list and make them take on the latest customizer changes.

**Comment by FlunkyDave** [comment]
Ah! Cool! Thanks alot!
It should have been for DLC guns too, though. :sob:
