### ISSUE TITLE
[Weapon Customization] How do I scroll the right sidebar, if the text does not fit the screen?

### ISSUE THREAD

**Issue by AmperAndSand** [JamesWilko/GoonMod#34]
I'm asking because I can't view or click on some of the lower text in the right sidebar, as they don't fit in the screen, and need to be scrolled. However, I can't scroll the right sidebar. My screen resolution is 1366 x 768. See this screenshot (part I can't view is highlighted):

[![][1]][2]

[1]: http://i.imgur.com/8iwHIfUl.jpg
[2]: http://i.imgur.com/8iwHIfU.jpg

**Comment by JamesWilko** [comment]
I'll implement a way to scroll on lower resolutions hopefully in the next update, until then there's nothing I can do for you.

**Comment by JamesWilko** [comment]
The parts panel should be scrollable as of BLT release.
