### ISSUE TITLE
Is there a way to turn the screen flashes back on?

### ISSUE THREAD

**Issue by Penguininnabox** [JamesWilko/GoonMod#35]
After one of the updates, the screen wont flash after you get shot, flashbanged, or dodge a bullet. It seemed nice at first, but its kind of hard to tell when I take heavy damage, is there any way to get the flashes back?

**Comment by JamesWilko** [comment]
Turn Colour Grading off. This is a side effect from using a different colour grading than the default or Payday+ (which is the default). Eventually I'll have a fix or change issued, but it's a complicated issue and takes a lot of time, so for now turn off or use the default colour grading.

**Comment by Penguininnabox** [comment]
Ok that worked, but just so you know, I did have both the gradings set to default and it stilll removed the flashes.

**Comment by JamesWilko** [comment]
In-game colour grading removed, no longer an issue with latest.
