### ISSUE TITLE
Inconsistent laser color with akimbo weapons

### ISSUE THREAD

**Issue by LouisTakePILLz** [JamesWilko/GoonMod#36]
Laser colors aren't set properly on akimbo pistols for other peers using the "Use their colour" option.
Only a single laser beam is affected for other players while both are for the client.

Here's a screenshot demonstrating the issue:
![image](https://cloud.githubusercontent.com/assets/920910/5789489/e8692d30-9e3a-11e4-9980-e48b4ab960ed.png)

In the screenshot above, both players were using the "rainbow laser color".

**Comment by JamesWilko** [comment]
Both lasers on akimbo weapons should use the correct colour as of BLT release.
