### ISSUE TITLE
Cut-off text below the stats table (within the "BlackMarketGUI")

### ISSUE THREAD

**Issue by LouisTakePILLz** [JamesWilko/GoonMod#37]
The title is rather self-explanatory, so no further explanation is really needed.

The following screenshot demonstrates the issue (contained within a red rectangle):
![image](https://cloud.githubusercontent.com/assets/920910/5789587/6f0c82f2-9e3f-11e4-89b9-6ad69af6f290.png)

Screen resolution: 1920x1080

This issue is highly related to #34.

**Comment by JamesWilko** [comment]
Text should no longer be cut-off as of BLT release.
