### ISSUE TITLE
Can't use crime.net cargo

### ISSUE THREAD

**Issue by buttpug** [JamesWilko/GoonMod#38]
the crime.net cargo option doesn't show up for me even though i have crime.net cargo enabled the only other mod i have is hoxhud but i tried unninstalling it and still not working
![2015-01-19_00002](https://cloud.githubusercontent.com/assets/10605034/5809147/60f86a58-a01c-11e4-9fd7-b59d5f0e2eed.jpg)
![2015-01-19_00003](https://cloud.githubusercontent.com/assets/10605034/5809148/60ffea62-a01c-11e4-9991-6d2813845a46.jpg)

**Comment by LouisTakePILLz** [comment]
Judging by the background on the first screenshot, you're trying to access the Crime.net cargo while on the main menu; you have to be in a lobby in order to use this feature.

**Comment by buttpug** [comment]
oh, makes sense, i thought it worked differently thank you
