### ISSUE TITLE
Not working with new HoxHud update

### ISSUE THREAD

**Issue by TheLoot** [JamesWilko/GoonMod#39]
The latest update has a new IPHLPAPI.dll file and it looks like Goonmod won't work with it.

Not really your issue, but just bringing it up for the poor folks like me that use them both.

**Comment by bakarafa** [comment]
yes...

**Comment by JamesWilko** [comment]
An update to use the new lua hook will hopefully be released tonight.

**Comment by JamesWilko** [comment]
Should be working with HoxHud again with the latest update.

**Comment by bakarafa** [comment]
it is working now, thanks :)
