### ISSUE TITLE
Weapon Customization Crashes?

### ISSUE THREAD

**Issue by FNFiveseveN** [JamesWilko/GoonMod#40]
Seems to crash when i try to customize a weapon/preview/launch session while using customized weapon.

Edit: Crash log says: Application has crashed: C++ exception
goonbase/mods/weapon_customization.lua:473: attempt to call method 'set_texture' (a nil value)

**Comment by JamesWilko** [comment]
The Bomb update broke the weapon customization, so attempting to preview a weapon or play a heist while the customization mod is active will crash your game. Turn off the customization and disable the version check bypass until the next update comes out tonight, your customized weapons will be saved, you won't lose them.

**Comment by FNFiveseveN** [comment]
thank you based wilko

**Comment by JamesWilko** [comment]
Weapon Customizer should be working crash free again. Lion's Roar Rifle and LEO Pistol customizer-ready materials will be out later on.

**Comment by FNFiveseveN** [comment]
sounds good, so dont customize my leo or roar yet?

**Comment by JamesWilko** [comment]
You can customize them, it just won't display until later.
