### ISSUE TITLE
Gage Coins

### ISSUE THREAD

**Issue by MERFYS** [JamesWilko/GoonMod#42]
Hi ! I not can buy some weapon mods & mask with gage goins (imgur.com/a/AHq21#1) 
It possible to fix it ? Or this open only achievements ?

Sorry for my bad english =)

**Comment by Qsaws** [comment]
you can't buy dlc items with gage coins

**Comment by MERFYS** [comment]
But Gage Assault, History pack i buy with gage coins

**Comment by JamesWilko** [comment]
You can't buy weapon parts that are unlocked via achievements since you get as many of them as you want after you unlock the achievement. Masks and mask mods can only be bought after you complete the achievements to unlock them, and if you own the DLC.
