### ISSUE TITLE
Modification menu empty after the manual update

### ISSUE THREAD

**Issue by Qsaws** [JamesWilko/GoonMod#43]
The title says it all, i use hoxhud with this mod and had no problem so far from that.

**Comment by JamesWilko** [comment]
Hotfix for U52 came out and the mod disabled itself to prevent any crashes. Either wait for the next update, or click "Ignore Unsupported Version" in the options menu. And next time pay attention to the big screen that pops up telling you the mod has been disabled.

**Comment by Qsaws** [comment]
Well after the manual update there is no pop up. But thanks.

**Comment by TheLoot** [comment]
Make sure to restart after choosing the "ignore" option on the menu, too.
