### ISSUE TITLE
No modifications appear in menu (latest version)

### ISSUE THREAD

**Issue by walale12** [JamesWilko/GoonMod#45]
The only thing that appears in the goonmod modifications menu is the help button:
![2015-01-26_00001](https://cloud.githubusercontent.com/assets/10388655/5907750/7c3569ec-a599-11e4-8a9e-ba1103954f47.jpg)

**Comment by TheLoot** [comment]
Small game update. Don't know about any issues since it was apparently a texture fix, but go to the Goonmod options, disable the version check, and restart your game.
