### ISSUE TITLE
modifications not working

### ISSUE THREAD

**Issue by sulphuricanus** [JamesWilko/GoonMod#47]
me and a couple of friends are having trouble installing the mod. modifications aren't showing up for some of us. we have no other mods downloaded and we have everything installed properly i think. do you need to extract the files still even though they aren't in a zip file?

**Comment by JamesWilko** [comment]
If the GoonMod menu is in options, then select "Ignore Unsupported Version" since the latest hotfix will disable the mod otherwise. If there is no GoonMod menu in options, then you didn't install the mod properly.
