### ISSUE TITLE
Lions Roar/LEO/New mods Weapon customization

### ISSUE THREAD

**Issue by FNFiveseveN** [JamesWilko/GoonMod#50]
Any ETA on when it might be coming? Sorry if this is the wrong place to ask this question i couldnt find a steam group or anything for my favorite misc mod.

EDIT: im a blind bat, just saw the contact info.

**Comment by JamesWilko** [comment]
Putting issues directly on GitHub is the best way to get stuff fixed. Contact info is just there for other reasons if needed.

Lions Roar and LEO customization overrides were published a while ago, AK Mod Pack overrides will be uploaded once I've finished extracting the new files.
You can redownload them from here: [Weapon Customizer Mod Overrides](https://github.com/JamesWilko/GoonMod/archive/WeaponCustomizerModOverrides.zip) and I'll post again once the new ones are up.

**Comment by JamesWilko** [comment]
Ok, overrides updated. Now contains the AK Mod Pack ones too.
Download: [Weapon Customizer Mod Overrides](https://github.com/JamesWilko/GoonMod/archive/WeaponCustomizerModOverrides.zip)

**Comment by Voltz42** [comment]
hmm,  I tried the mod override and it didn't work... still unable to buy leo mods with gage coins

**Comment by JamesWilko** [comment]
Mod overrides are only for customizing how weapons look, not the mod shop.
