### ISSUE TITLE
crime.net cargo duplicates dlc weapon mods.

### ISSUE THREAD

**Issue by Kryoten** [JamesWilko/GoonMod#52]
Hi James,

When I trade weapons with dlc mods on them to my friends, it seems to duplicate them as a separate non-dlc listing, i.e. getting a Lion's Roar with the Precision barrel creates a separate listing for the Precision Barrel under the barrels category. This new listing does not have the "This is part of the Clover/Dragan/Gage Courier Mod/ Pack!". Trying it with a non-dlc weapon mods does not duplicate the item, like with the standard suppressor.

**Comment by Sethycakes** [comment]
Any ETA on when Cargo's coming back?
