### ISSUE TITLE
"No Material" on Mask causes non-GoonModders to crash?

### ISSUE THREAD

**Issue by TheLoot** [JamesWilko/GoonMod#53]
Happened in a lobby with two friends. One made a Gage Blade with No Material and it crashed the other person who doesn't use GoonMod.

**Comment by JamesWilko** [comment]
Looks like the No Material is showing up in mask customization when it shouldn't be. I'll patch it in with the compatibility update to fix it, but your friend is going to have to delete the mask with it on, or else it'll keep crashing people.

**Comment by TheLoot** [comment]
Fixed as soon as we figured it out, so it won't be a problem, and we now know to avoid that while it lasts.

**Comment by JamesWilko** [comment]
Should be unable to use No Material in masks now. If it shows up still with the latest version, reopen this and yell at me.
