### ISSUE TITLE
excessive force not working properly

### ISSUE THREAD

**Issue by victorchanchan956** [JamesWilko/GoonMod#54]
sometimes when i play hoxton breakout heist (ovk)
the mutator only spawms normal cops 
cloker and tazers come out like 1 or 2 then they stop spawning
after that it will keep spawning normal cops  and stop spawning specail units

**Comment by JamesWilko** [comment]
The Excessive Force and National Guard Response mutators are going to be rewritten for the new version to hopefully make them work better. No ETA, but it's on the list.

**Comment by victorchanchan956** [comment]
so its gonna be fixed or its already fixed?

**Comment by JamesWilko** [comment]
To be fixed, not yet.

**Comment by victorchanchan956** [comment]
but its pretty strange that there  is no update on the mutator why would it suddenly wen t wrong?
did payday change its spawn system ?

**Comment by JamesWilko** [comment]
Mutators are now an official feature, so GoonMod mutators have been removed. Closing all issues relating to mutators.
