### ISSUE TITLE
Leo weapons mods

### ISSUE THREAD

**Issue by Voltz42** [JamesWilko/GoonMod#55]
Downloaded the override from here: https://github.com/JamesWilko/GoonMod/issues/50

still unable to purchase any leo weapon mods with gage coins

**Comment by JamesWilko** [comment]
The mods for the Leo pistol are achievement locked but they don't actually give you a copy of the mod. I'll fix this, but it won't be integrated into the "release" version until the new version is completed.

**Comment by JamesWilko** [comment]
LEO weapon mods should be purchasable as of BLT release.
