### ISSUE TITLE
Crime.net Cargo disabled, why?

### ISSUE THREAD

**Issue by Sethycakes** [JamesWilko/GoonMod#56]
Hi, I know this is not really an issue and it was likely disabled for a good reason but I just want to know why. Earlier today before the update (when Goonmod was running on an unsupported Payday 2 version), I sent someone a mask using Crime.net Cargo and it worked fine.

**Comment by JamesWilko** [comment]
I disabled it since there's a bunch of edge cases which aren't going to be fixed until the new version of GoonMod comes out. DLC items being traded away and not being able to be retrieved and stuff like that. It'll be coming back, just not until the new version is ready and released.

**Comment by Sethycakes** [comment]
That's all I wanted to know, thanks! I absolutely love the mod, keep up the great work!
