### ISSUE TITLE
excessive force not working properly#2

### ISSUE THREAD

**Issue by victorchanchan956** [JamesWilko/GoonMod#57]
in other mission this issue sometimes happens too
at the begining of the mission alot of normal cops are spawned 
then after a few mintues it only keeps spawning cloaker  (sometimes tazer  )and normal cops and nothing else different come out in the whole mision
and sometimes it only came out like 5 or 6 special enemy from the begining to the end

**Comment by JamesWilko** [comment]
This is the same issue as the other one you created, it doesn't need to be reported twice.
