### ISSUE TITLE
I'm not sure how confirmed this is BUT.

### ISSUE THREAD

**Issue by BarclayTech** [JamesWilko/GoonMod#60]
Whenever I terminate a contract or even switch between days (finish day 1, go to day 2), GoonMod likes to crash. It doesn't happen 100% of the time when going from Day 1 to 2 to 3, but there's a high chance.

Seems also whenever I terminate a contract, it crashes. I've fiddled around, loaded some personal scripts of mine alongside GoonMod, disabled them, loaded PocoHud, disabled it and no matter what, even if ONLY GoonMod is loaded, the game will crash when terminating a contract or exit to the main menu.

**Comment by JamesWilko** [comment]
Can you upload, or send me, your crash logs after having a crash, so that I can see what your problem is. You'll find them in %appdata%/Local/PAYDAY 2/, and I'll need crash.txt and crashlog.txt

**Comment by BarclayTech** [comment]
I don't ever get Crash logs from Payday. I only ever get he Mini-Dump files.

**Comment by goontest** [comment]
try validating game files

**Comment by BarclayTech** [comment]
I have, everything is validated and up to date.

Still happens, gonna have to remove GoonMod until there's a fix.

**Comment by JamesWilko** [comment]
Nothing in the editor folder is modified by GoonMod, and especially nothing concerning loading level packages. Completely clean your entire Payday installation of mods, and then try installing them one by one until you can recreate the crash.

**Comment by BarclayTech** [comment]
I did as you suggested. I loaded everything 1 by 1 except goonmod, not crash, then I loaded a freshly downloaded goonmod and it crashed.

I then went back and removed everything else, just kept goonmod, and it then crashed again.
