### ISSUE TITLE
ive installed GoonMod using the BLT stuff however im not seeing any goonmod menus show up, did i do the wrong?

### ISSUE THREAD

**Issue by FNFiveseveN** [JamesWilko/GoonMod#64]
notihng in the mod optiuons menu either, all i see is canary.

**Comment by Xemrox** [comment]
afaik ive pasted the BLT mods folder in the main payday folder and moved the new GoonMod folder into this one.

**Comment by FNFiveseveN** [comment]
thats what i did, i just put the entire folder i nthere, right? dont take anything else out?

**Comment by Xemrox** [comment]
idk used http://paydaymods.com/wp-content/uploads/2015/03/GoonMod.zip and got this structure:
* Payday 2\mods
* Payday 2\mods\GoonMod
* Payday 2\mods\base
* Payday 2\mods\logs
* Payday 2\mods\saves

also replaced
* Payday 2\IPHLPAPI.dll

**Comment by FNFiveseveN** [comment]
Figured it out, i used the github version, not the new site version. my bad
