### ISSUE TITLE
Corpse delimiter bugs.

### ISSUE THREAD

**Issue by HFSucks** [JamesWilko/GoonMod#66]
It seems to make cops invincible. Shooting them drains my clip away ridiculously fast until I need to reload. Meleeing them causes me to get stuck so that I keep hitting them and the camera slowly spins off in one direction until I look or get hit away. Each hit also causes them to drop ammo as if they were killed.

https://www.youtube.com/watch?v=IDm26MzgRDM

**Comment by JamesWilko** [comment]
This should be fixed with the update that just went out. Despawn Shields was causing an issue because of a global that didn't exist anymore.
