### ISSUE TITLE
Where is the latest non-development branch of GoonMod?

### ISSUE THREAD

**Issue by Sethycakes** [JamesWilko/GoonMod#69]
Hi, I went to here https://github.com/JamesWilko/GoonMod to download the GoonMod update, but it said that this is the development branch. I did not want to have to use Payday 2 BLT because I use HoxHud, so I tried to find a non-development branch. However, I can't find a non-development version besides the legacy branch and that branch doesn't have the latest update.

**Comment by JamesWilko** [comment]
The readme needs to be updated, but a non-BLT version is no longer being maintained by myself.
