### ISSUE TITLE
Weapon Customization not working

### ISSUE THREAD

**Issue by Davidj361** [JamesWilko/GoonMod#72]
[Here's a recording of what's happening.](https://www.youtube.com/watch?v=3bLpFqJuBBY)

**Comment by LAForsman** [comment]
I'm having the exact same problem tried everything cant figure it out

**Comment by JamesWilko** [comment]
I accidentally uploaded a release which didn't come with the Customizer Overrides, please download the zip file from the [release page](https://github.com/JamesWilko/GoonMod/releases/latest) and put the GoonModWeaponCustomizer in assets/mod_overrides.

**Comment by Davidj361** [comment]
```
[Mods] Could not read or find mod.txt for modification: GoonModWeaponCustomizer
[Error] Could not load revision file for GoonMod Weapon Customizer!
```
It's still not working.
