### ISSUE TITLE
Inventory bugs out with new update (Non-beta)

### ISSUE THREAD

**Issue by A-Mooing-Dragon** [JamesWilko/GoonMod#79]
Friend is having the same issue, with only GoonMod installed. Opening the inventory anywhere causes this to happen, consistently, and the game softlocks: http://steamcommunity.com/sharedfiles/filedetails/?id=434975694

**Comment by tiddy** [comment]
+1. Identical Issue. Locks on inventory screen. Identical image.

**Comment by De3xter** [comment]
https://github.com/goontest/GoonMod/blob/0d6df7b46a544140e2a1b513bf53940dbddb5824/GoonMod/lua/BlackMarketGUI.lua follow intructions

**Comment by goontest** [comment]
https://github.com/goontest/GoonMod/archive/master.zip 
replace goonmod/lua/blackmarketgui.lua for inventory fix and goonmod/goonbase.lua to re enable goonmod
