### ISSUE TITLE
inventory is gone ( goonmod legacy)

### ISSUE THREAD

**Issue by victorchanchan956** [JamesWilko/GoonMod#83]

**Comment by AUZShinobi** [comment]
After the Western weapon DLC. Major Inventory glitch. If it is updated already then PD2BLT isn't showing.

**Comment by goontest** [comment]
It hasn't been updated the following will fix it
https://github.com/goontest/GoonMod/archive/master.zip 
replace goonmod/lua/blackmarketgui.lua for inventory fix and goonmod/goonbase.lua to re enable goonmod

**Comment by JamesWilko** [comment]
Legacy branch is no longer maintained, it is only a reference for the older version of GoonMod.
