### ISSUE TITLE
Exiting the game without visiting the main menu deletes all recently purchased gagecoin items

### ISSUE THREAD

**Issue by admiralPanic** [JamesWilko/GoonMod#85]
Bought the rainbow material for 3 coins, exited the mask customization menus, then restarted the game. Both rainbow and my gage coins didn't show up after that. The same thing happened with a color on a different occasion.

**Comment by TheLoot** [comment]
The game doesn't save unless you exit the inventory, but Goonmod isn't tied to that.

**Comment by JamesWilko** [comment]
Extended Inventory now only saves when the game itself saves data, so purchasing items won't save the spent Gage Coins if you quit without the game saving.
