### ISSUE TITLE
Removing corpses in stealth

### ISSUE THREAD

**Issue by sebastiangabl** [JamesWilko/GoonMod#87]
When you set a hotkey to remove corpses and instantly press it after you kill a guard in stealth, you don't have to answer the pager. should be fixed asap. Sorry boys no unlimited pagers for you :P

**Comment by pepe1987** [comment]
really?
this has nothing to do with the mod, this is game fault.

**Comment by sebastiangabl** [comment]
Not really, since in the base game you can't remove corpses. So whenever the game is in stealth it just doesn't remove any corpses until the game has gone loud. But with goon mod you can force the game to remove corpses so no more need for pagers, bodybags pretty much anything in stealth. Just disable corpse removal as long as the game is still stealth, should fix the issue.

**Comment by pepe1987** [comment]
Ok, I see what you mean, indeed there is no check if you are in stealth or loud

+1, need to be fixed

    GoonBase.CorpseDelimiter.DoRemoveAllCorpses = function(self)
        if managers.enemy then
            managers.enemy:dispose_all_corpses()
        end
    end

**Comment by goontest** [comment]
replacing PAYDAY 2\mods\GoonMod\modsbody_count.lua with below should fix it
https://github.com/goontest/GoonMod/blob/master/GoonMod/mods/body_count.lua

**Comment by sebastiangabl** [comment]
Looks good, thanks for looking into it.
