### ISSUE TITLE
Can't buy mask Materials, Patterns, or Colors with Gage Coins

### ISSUE THREAD

**Issue by MikeGamerGuy** [JamesWilko/GoonMod#93]
I don't know if it was working before the grin update or not, but it's not working now.  Buying masks and and weapon mods still seems to work.

**Comment by JohnnyyBoy** [comment]
I also have the same issue, I can buy everything else but the customization items

**Comment by WorldEaterYT** [comment]
Yeah I just spend 3 damn points trying to buy a material :( :-1: PLEASE FIX THIS

**Comment by WorldEaterYT** [comment]
*italic* If there is anyway I can get my coins back that would be awesome! *italic*

**Comment by JamesWilko** [comment]
Mask mods now update as soon as you buy them, instead of having to quit the menu and re-open it.
