### ISSUE TITLE
Valkyria rifle scope mount model changed in recent patch

### ISSUE THREAD

**Issue by Isotaupe** [JamesWilko/GoonMod#95]
Hey, not sure if this is the best place for this, but I noticed that since the Ninja DLC dropped the Valkyria scope mount model changed. When GoonmodWeaponCustomizer is in the mod_overrides folder, it appears textureless. Screenshot attached.
![2015-07-22_00001](https://cloud.githubusercontent.com/assets/11800838/8832024/514f826a-3074-11e5-99ab-3a8671bacadd.jpg)

**Comment by Isotaupe** [comment]
Looking at the unchanged third-person model, this might be unintended. 
![2015-07-22_00002](https://cloud.githubusercontent.com/assets/11800838/8833341/f6b07622-307b-11e5-98ae-d483548180e5.jpg)

**Comment by JamesWilko** [comment]
Fixed this in yesterdays customizer overrides update. The scope mount now points to the correct texture.
