### ISSUE TITLE
Interacting With Civs Broken In Newest Release

### ISSUE THREAD

**Issue by MadCrayolaz** [JamesWilko/GoonMod#97]
After updating to the newest version, I can no longer interact with civs.  When I press the interact to get them down, no sound plays, no animation plays, and they do not respond.  When killed, if they have an exclamation point above their head, they maintain that.  As well, when they are body bagged, they body remains, and a body bag is used.

I checked the logs, and it reported these errors:
02:59:01 PM FATAL ERROR: mods/GoonMod/dialogs/ScalableTextBoxGUI.lua
02:59:01 PM FATAL ERROR: attempt to call a string value
02:59:01 PM FATAL ERROR: mods/GoonMod/dialogs/RedeemCodeDialog.lua
02:59:01 PM FATAL ERROR: attempt to call a string value
02:59:01 PM FATAL ERROR: mods/GoonMod/dialogs/RedeemCodeItemsDialog.lua
02:59:01 PM FATAL ERROR: attempt to call a string value
02:59:10 PM FATAL ERROR: mods/GageHud/Lua/EnemyManager_ext.lua:118: attempt to perform arithmetic on a nil value
02:59:10 PM FATAL ERROR: mods/GageHud/Lua/EnemyManager_ext.lua:118: attempt to perform arithmetic on a nil value
02:59:10 PM FATAL ERROR: mods/GageHud/Lua/EnemyManager_ext.lua:118: attempt to perform arithmetic on a nil value
02:59:10 PM FATAL ERROR: mods/GageHud/Lua/EnemyManager_ext.lua:118: attempt to perform arithmetic on a nil value
02:59:10 PM FATAL ERROR: mods/GageHud/Lua/EnemyManager_ext.lua:118: attempt to perform arithmetic on a nil value
02:59:10 PM FATAL ERROR: mods/GageHud/Lua/EnemyManager_ext.lua:118: attempt to perform arithmetic on a nil value
02:59:10 PM FATAL ERROR: mods/GageHud/Lua/EnemyManager_ext.lua:118: attempt to perform arithmetic on a nil value
02:59:10 PM FATAL ERROR: mods/GageHud/Lua/EnemyManager_ext.lua:118: attempt to perform arithmetic on a nil value
02:59:10 PM FATAL ERROR: mods/GageHud/Lua/EnemyManager_ext.lua:118: attempt to perform arithmetic on a nil value
02:59:10 PM FATAL ERROR: mods/GageHud/Lua/EnemyManager_ext.lua:118: attempt to perform arithmetic on a nil value
02:59:10 PM FATAL ERROR: mods/GageHud/Lua/EnemyManager_ext.lua:118: attempt to perform arithmetic on a nil value
02:59:10 PM FATAL ERROR: mods/GageHud/Lua/EnemyManager_ext.lua:118: attempt to perform arithmetic on a nil value
02:59:10 PM FATAL ERROR: mods/GageHud/Lua/EnemyManager_ext.lua:118: attempt to perform arithmetic on a nil value
02:59:10 PM FATAL ERROR: mods/GageHud/Lua/EnemyManager_ext.lua:118: attempt to perform arithmetic on a nil value
02:59:10 PM FATAL ERROR: mods/GageHud/Lua/EnemyManager_ext.lua:118: attempt to perform arithmetic on a nil value
02:59:10 PM FATAL ERROR: mods/GageHud/Lua/EnemyManager_ext.lua:118: attempt to perform arithmetic on a nil value
02:59:16 PM Lua: [4] MadCrayolaz: GNAP/gmcpwlc/r:1|g:1|b:1|a:1
02:59:16 PM FATAL ERROR: mods/GageHud/Lua/EnemyManager_ext.lua:118: attempt to perform arithmetic on a nil value
02:59:17 PM FATAL ERROR: [string "lib/units/enemies/cop/logics/coplogicarrest..."]:851: attempt to index a nil value
02:59:17 PM FATAL ERROR: mods/GageHud/Lua/EnemyManager_ext.lua:118: attempt to perform arithmetic on a nil value

I'm currently using this with GageHUD and PocoHud for extra features, but any overlapping features have been disabled in their respective mods, so they shouldn't be attempting to call code multiple times for the same event.

**Comment by JamesWilko** [comment]
Not a GoonMod issue.
