### ISSUE TITLE
Push to Interact Minimum Interaction time

### ISSUE THREAD

**Issue by MikeGamerGuy** [JamesWilko/GoonMod#99]
Goonmod Revision 17
push_to_interact.lua
Line 129
local interaction = (interaction_data.timer or 10) >= PushToInteract:MinimumInteractionTime()

This seems to be returning true when I'm expecting it to be false, resulting in push to interact being always on.  I determined this by replacing the boolean expression with "false", and the module behaved as expected in game. I didn't test if "interaction_data.timer" actually works, because I don't know how.  If anyone knows how to fix it, I'd be grateful.

**Comment by kazritsu** [comment]
Can you post how it looks like now?
I'm not well versed with words like boolean expression and I've been trying to fix this problem for some time now
Thank you

**Comment by MikeGamerGuy** [comment]
It looks the same as it did before because I don't know how to fix it.

The line
local interaction = (interaction_data.timer or 10) >= PushToInteract:MinimumInteractionTime()
is storing TRUE in the "interaction" variable when i'm expecting it to store FALSE in the "interaction" variable.  I can only assume that interaction_data.timer is "NULL" or something along those lines, resulting in 10 being >= PushToInteract:MinimumInteractionTime(), meaning the expression is TRUE.  But I don't know how to test "interaction_data.timer", because I'm not familiar with modding payday 2.

**Comment by JamesWilko** [comment]
Fixed in r21
